@jwtToken = ...

### Bot test
POST https://us-central1-match-guru-0iqc9r.cloudfunctions.net/bot
Authorization: Bearer ...
Content-Type: application/json

{
    "message": "hi",
    "timezone":"Europe/Berlin",
    "chat_id": 10,
    "game_id": null
}
