@jwtToken = ...

### Bot test
POST https://us-central1-match-guru-0iqc9r.cloudfunctions.net/bot
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "message": "list all eu leagues",
    "timezone":"Europe/Berlin",
    "chat_id": 10,
    "game_id": null
}


### Bot test
POST http://localhost:8080/bot
Content-Type: application/json

{
    "message": "hi",
    "timezone":"Europe/Berlin",
    "chat_id": 10,
    "game_id": null
}

### Get all leagues
GET https://api.sportmonks.com/v3/football/leagues?include=country:name&per_page=100&page1
Content-Type: application/json
Authorization: E5fp0YupbTOX0Y8HyHLCvLZ0guAzQGndg8Ftpcm1h8gxKvrj18jGKnvcR98K

### get all teams
GET https://api.sportmonks.com/v3/football/teams?
Content-Type: application/json
Authorization: E5fp0YupbTOX0Y8HyHLCvLZ0guAzQGndg8Ftpcm1h8gxKvrj18jGKnvcR98K

### search team
GET https://api.sportmonks.com/v3/football/teams/search/van bb?per_page=100&page1
Content-Type: application/json
Authorization: E5fp0YupbTOX0Y8HyHLCvLZ0guAzQGndg8Ftpcm1h8gxKvrj18jGKnvcR98K
