name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' # https://cloud.google.com/functions/docs/runtime-support#go
        cache: true


    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-1.23-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-1.23-
          ${{ runner.os }}-go-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

    - name: Run Tests with Coverage
      run: go test -v -coverprofile=coverage.out ./...

    - name: Display Coverage Summary
      if: success()
      run: |
        go tool cover -func=coverage.out | grep total
